package wunc:handlers;

interface http {
  variant method {
    get,
    head,
    post,
    put,
    delete,
    connect,
    options,
    trace,
    patch,
    other(string)
  }

  record request {
    method: method,
    url: string
  }

  record response {
    status: u16
  }

  handle: func(req: request) -> response;
}

interface read-writer {
  read: func(n: s32) -> tuple<list<u8>, s32>;
  write: func(data: list<u8>) -> s32;
}

world handlers {
  export http;
  import read-writer;
}
