#!/usr/bin/env bash

set -eo pipefail

ROOT=$(realpath "$(dirname "$0")/..")

build_tinygo() {
  DIR="$ROOT/examples/tinygo"
  DIST="$DIR/dist"
  mkdir -p "$DIST"
  pushd "$DIR" > /dev/null
  echo "Building tinygo example..."
  tinygo build -target=wasip2 -o "$DIST/example.tinygo.wasm" --wit-package ../../wit/ --wit-world functions
  popd > /dev/null
}

build_rust() {
  DIR="$ROOT/examples/rust"
  pushd "$DIR" > /dev/null
  echo "Building rust example..."
  cargo build --release --target wasm32-wasip2
  popd > /dev/null
}

# build_tinygo
build_rust
