#!/usr/bin/env bash

set -eo pipefail

ROOT=$(realpath "$(dirname "$0")/..")

if ! command -v wkg &> /dev/null; then
  echo "wkg is not installed: https://github.com/bytecodealliance/wasm-pkg-tools"
  exit 1
fi

pushd "$ROOT" > /dev/null
wkg wit fetch
popd > /dev/null
