name: cargo

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - run: cargo build --verbose
      - run: cargo test --verbose
