name: cargo

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: script/init
    - run: cargo build --verbose
    - run: cargo test --verbose
